import Head from "next/head";
import { Inter } from "next/font/google";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import { Suspense, useState } from "react";
import ObjectScene from "@/components/ObjectScene";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [grab, setGrab] = useState<boolean>(false);
  const [ambientOn, setAmbientOn] = useState<boolean>(true);
  const [pointLightOn, setPointLightOn] = useState<boolean>(true);
  return (
    <>
      <Head>
        <title>3D Viewer Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          padding: 20,
          backgroundColor: "rgba(0,0,0,0.5)",
        }}
      >
        <span style={{ marginRight: 10 }}>
          <button
            onClick={() => setAmbientOn((prev) => !prev)}
            style={{ padding: 10, borderRadius: 10 }}
          >
            AmbientLight On/Off
          </button>
        </span>
        <span>
          <button
            onClick={() => setPointLightOn((prev) => !prev)}
            style={{ padding: 10, borderRadius: 10 }}
          >
            PointLight On/Off
          </button>
        </span>
      </div>
      <main
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          height: 1000,
          cursor: grab ? "grabbing" : "grab",
        }}
      >
        <Canvas
          dpr={[1, 2]}
          shadows
          camera={{
            fov: 45,
            near: 0.1,
            far: 100,
            position: [-1.5, 1.5, 1.5],
          }}
          onMouseDown={() => setGrab(true)}
          onMouseUp={() => setGrab(false)}
          style={{ height: "100%", position: "absolute" }}
        >
          <Suspense fallback={null}>
            {ambientOn && <ambientLight />}
            {pointLightOn && <pointLight position={[50, 50, 50]} />}
            <ObjectScene
              url={"/models/baked_mesh.obj"}
              mtl={"/models/baked_mesh.mtl"}
              colorMap={"/models/baked_mesh_tex0.png"}
              normalMap={"/models/baked_mesh_norm0.png"}
              aoMap={"/models/baked_mesh_ao0.png"}
            />
            <OrbitControls target={[0, 0, 0]} enableDamping />
          </Suspense>
        </Canvas>
      </main>
    </>
  );
}
